### ISSUE TITLE
Submitting prework

### ISSUE THREAD

**Issue by nnti3n** [thienphong215/simple-blog#1]
This is my pre-work submission 
/cc @coderschoolreview

**Comment by coderschoolreview** [comment]
### Thank you for your Rails submission, thienphong215!

:no_entry: Unfortunately **there are some problems** with your submission:
- I couldn't find how much time you spent on the assignment. Please include the number of hours spent on your assignment in your `README.md`.

**Comment by nnti3n** [comment]
I fixed it.
